<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworks);netstandard2.0</TargetFrameworks>
    <RootNamespace>L10NSharp</RootNamespace>
    <Description>L10NSharp is a .NET localization library. It collects strings which need localization when your application first runs and saves them in a XLIFF file.</Description>
    <AssemblyTitle>L10NSharp</AssemblyTitle>
    <PackageId>L10NSharp</PackageId>
    <PackageProjectUrl>https://github.com/sillsdev/l10nsharp</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0" PrivateAssets="all" />
    <PackageReference Include="JetBrains.Annotations" Version="2026.2.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="SIL.ReleaseTasks" Version="3.3.0" PrivateAssets="all" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.11" />
  </ItemGroup>
</Project>
